import type { NextPage } from 'next'
import Head from 'next/head'
import { Col, Container, Form, Row } from 'react-bootstrap';
import FormSection from '../src/components/formSection';
import Header from '../src/components/header';

import styles from './index.module.css';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>
      <Col className={styles.col}>
        <Header />
        <p>Please enter your name, email address and a message into the form below</p>
        <FormSection />
      </Col>
    </Container>
  )
}

export default Home
